services:
  TaskFlow.api:
    image: taskflow.api
    build:
      context: .
      dockerfile: TaskFlow.Api/Dockerfile
    ports:
      - "5166:80"
      - "5167:443"

  Rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  Consumer:
    image: consumer.worker
    build:
      context: .
      dockerfile: TaskFlow.WorkerService/Dockerfile
    depends_on:
      - Rabbitmq
    restart: on-failure
